name: Update Decrypt Feed

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

permissions:
  contents: write

concurrency:
  group: update-decrypt
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm install --no-audit --no-fund

      - name: Build decrypt.json
        run: npm run build:decrypt

      - name: Commit and push if changed
        run: |
          if git diff --quiet; then
            echo "No changes."
            exit 0
          fi

          git config user.name "ruin2itive-bot"
          git config user.email "ruin2itive-bot@users.noreply.github.com"

          git add data/decrypt.json
          git commit -m "Update decrypt feed"
          git push
