/* ruin2itive.org (static JSON feed render)
   - No CORS
   - Loads /data/*.json generated by GitHub Actions
*/

const SECTIONS = [
  { key: "crypto", title: "markets / crypto", take: 2 },
  { key: "hn", title: "hacker news", take: 2 },

  { key: "ap", title: "world news / associated press", take: 2 },
  { key: "reuters", title: "world news / reuters", take: 2 },
  { key: "bbc", title: "world news / bbc", take: 2 },

  { key: "ufo", title: "ufo / uap", take: 1 }
];

function $(sel) {
  return document.querySelector(sel);
}

function esc(s) {
  return String(s || "")
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}

function fmtDate(iso) {
  if (!iso) return "";
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return "";
  // compact: YYYY-MM-DD
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, "0");
  const day = String(d.getDate()).padStart(2, "0");
  return `${y}-${m}-${day}`;
}

function ensureLowercaseBrand() {
  // You asked: never caps. Always lowercase.
  const el = $("#siteTitle");
  if (el) el.textContent = "ruin2itive";
}

function renderItems(container, payload, take) {
  // stable: always render something (items or fallback)
  const items = (payload?.items || []).slice(0, take);

  if (items.length === 0) {
    const msg = payload?.error ? "unavailable" : "loading…";
    container.innerHTML = `<div class="feed-empty"><em>${esc(msg)}</em></div>`;
    return;
  }

  container.innerHTML = items
    .map((it) => {
      const title = esc(it.title);
      const url = esc(it.url);
      const date = fmtDate(it.date);
      const meta = date ? `<span class="item-meta">${esc(date)}</span>` : "";
      return `
        <div class="feed-item">
          <a class="feed-link" href="${url}" target="_blank" rel="noopener noreferrer">${title}</a>
          ${meta}
        </div>
      `;
    })
    .join("");
}

async function loadJson(key) {
  const res = await fetch(`data/${key}.json`, { cache: "no-store" });
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  return await res.json();
}

async function boot() {
  ensureLowercaseBrand();

  for (const s of SECTIONS) {
    const mount = document.querySelector(`[data-feed="${s.key}"]`);
    if (!mount) continue;

    // show immediate stable placeholder
    mount.innerHTML = `<div class="feed-empty"><em>loading…</em></div>`;

    try {
      const payload = await loadJson(s.key);
      renderItems(mount, payload, s.take);
    } catch (e) {
      renderItems(mount, { error: "unavailable", items: [] }, s.take);
    }
  }
}

document.addEventListener("DOMContentLoaded", boot);
