name: build-feeds

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "*/30 * * * *"  # every 30 minutes
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: build-feeds
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm ci || npm install

      - name: Build feeds
        run: npm run build:feeds

      - name: Commit data updates (if changed)
        run: |
          git config user.name "ruin2itive-bot"
          git config user.email "actions@users.noreply.github.com"
          git add data/*.json data/index.json || true
          git diff --cached --quiet && echo "No changes" && exit 0
          git commit -m "build: refresh feeds"
          git push
